### ISSUE TITLE
Bringing back ansicolors

### ISSUE THREAD

**Issue by turbotoni** [wazuh/wazuh-kibana-app#1464]
Hi Team!
Since the new Kibana 7 the Wazuh Plugin will crash the Apache 2 licensed Version of Kibana.
Seems like the "ansicolor" module is not present in the OSS version.
I am using Kibana 7.1.0 OSS and Wazuh App 3.9.1_7.1.0

https://www.elastic.co/downloads/kibana-oss

```
[root@561b45a7b850 ~]# ./kibana-7.1.0-linux-x86_64/bin/kibana
  log   [07:27:31.810] [fatal][root] { Error: Cannot find module 'ansicolors'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/root/kibana-7.1.0-linux-x86_64/plugins/wazuh/server/initialize.js:12:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at loader (/root/kibana-7.1.0-linux-x86_64/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/root/kibana-7.1.0-linux-x86_64/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/root/kibana-7.1.0-linux-x86_64/plugins/wazuh/init.js:14:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at loader (/root/kibana-7.1.0-linux-x86_64/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/root/kibana-7.1.0-linux-x86_64/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18) code: 'MODULE_NOT_FOUND' }

 FATAL  Error: Cannot find module 'ansicolors'
```

Regards

**Comment by jesusgn90** [comment]
Hi @turbotoni, 

I've just verified your issue.

**Description**

App installation fails in Kibana OSS version due to a missing dependency not included in the OSS version.

**Steps to reproduce**

```
curl -o kibana-oss-7.1.0-x86_64.rpm https://artifacts.elastic.co/downloads/kibana/kibana-oss-7.1.0-x86_64.rpm
yum install kibana-oss-7.1.0-x86_64.rpm 
sudo -u kibana /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.1_7.1.0.zip
systemctl restart kibana
```

**Proposal**

a) Include the dependency in our package.json.
b) Review the dependency usage, we may want to just remove it (it's a tool for giving colors to the stdout)

**Comment by jesusgn90** [comment]
Hello again @turbotoni,

We are going to remove `ansicolors` as a dependency. Looking at the code the only thing we are doing with that library is adding color to the word `wazuh` for some server logs. Using the `inspect` from Node.js I can see what generates the library is the next string: `'\u001b[34mwazuh\u001b[39m';` so we decided to just use that string a do not use the library.

Before:

```js
import colors from 'ansicolors';
const blueWazuh = colors.blue('wazuh');
```

After:

```js
const blueWazuh = '\u001b[34mwazuh\u001b[39m';
```

Here is the change https://github.com/wazuh/wazuh-kibana-app/commit/1832bb0963b58cbb94b01eb5a5b4dae32f756206.

Regards

**Comment by arunkumarmurugesan90** [comment]
Hi, I m still getting an error on the same version. 

wazuh version: 3.9.1
kibana-oss : 7.1.1
