### ISSUE TITLE
Wazuh ElasticStack Upgrade Errors

### ISSUE THREAD

**Issue by hafeezy2j** [wazuh/wazuh-kibana-app#162]
I have recently upgraded wazuh from 2.X to 3.X and now I'm getting following errors in  /var/log/elasticsearch/elasticsearch.log

[2017-12-26T13:24:51,876][DEBUG][o.e.a.b.TransportShardBulkAction] [wazuh-alerts-2017.12.26][0] failed to execute bulk item (index) BulkShardRequest [[wazuh-alerts-2017.12.26][0]] containing [18] requests
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [data]
        at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:302) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:485) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:500) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:394) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:384) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.index.mapper.DocumentParser.internalParseDocument(DocumentParser.java:93) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:67) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:261) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:708) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:686) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:667) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:548) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequest(TransportShardBulkAction.java:140) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:236) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:123) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:110) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:72) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1033) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1011) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:104) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:358) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:298) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:974) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:971) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:238) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2211) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:983) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.replication.TransportReplicationAction.access$500(TransportReplicationAction.java:97) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:319) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:294) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:281) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:652) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:637) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.1.0.jar:6.1.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.IllegalStateException: Can't get text on a START_OBJECT at 1:579
        at org.elasticsearch.common.xcontent.json.JsonXContentParser.text(JsonXContentParser.java:85) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.textOrNull(AbstractXContentParser.java:237) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.index.mapper.KeywordFieldMapper.parseCreateField(KeywordFieldMapper.java:315) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:297) ~[elasticsearch-6.1.0.jar:6.1.0]
        ... 38 more

Any clue what could be causing this ??

**Comment by havidarou** [comment]
Hi @hafeezy2j,

as I see, the errors refer to an 2.x index.

Are these errors stopping elasticsearch from execute?

Maybe the upgrading process wasn't correct.

Here's our upgrading guide: https://documentation.wazuh.com/current/installation-guide/upgrading/different_major.html#upgrading-different-major

One thing you can do (to check the new templates are correctly set up) is execute:

```curl localhost:9200/_cat/templates?v```

And another one, to see whether the reindex process of the Wazuh app configuration worked fine:

```curl localhost:9200/_cat/indices?v```

Please paste the output of those commands.

Regards.

**Comment by hafeezy2j** [comment]
Hello @havidarou 

I have followed the major upgrade guide but dont know what I have missed. Please see the attached file for curl output.

[output.txt](https://github.com/wazuh/wazuh-kibana-app/files/1589225/output.txt)

Thanks,

**Comment by havidarou** [comment]
Hi @hafeezy2j ,

everything seems to be fine.

The errors you mention, when do they exactly happen?

Regards.

**Comment by hafeezy2j** [comment]
Hello @havidarou 

Just after the upgrade. Elasticsearch and all other services are running fine as well..

Thanks,

**Comment by havidarou** [comment]
But what do you mean after the upgrade?

It gets prompted somewhere? or did you find it searching in the logs for no specific reason?

Regards.

**Comment by hafeezy2j** [comment]
@havidarou 

I'm just seeing above mentioned errors /var/log/elasticsearch/elasticsearch.log for no obvious reasons even though everything seems to be working fine... Is there anything I can do to stop them?

**Comment by havidarou** [comment]
Hi @hafeezy2j ,

I hadn't noticed them.

I'll investigate what could be happening, although my bet is it has nothing to do with the upgrading process, but with the older indexes in the new elasticsearch version.

Thanks for letting us know!

Regards.

**Comment by hafeezy2j** [comment]
Hello @havidarou 
Thank you and keep me posted.

**Comment by hafeezy2j** [comment]
Happy New Year @havidarou !

Did you get a chance to look in to this? I need to roll out this upgrade on our corporate network and just wondering if I it will safe to do it or I should wait for a fix/workaround for this issues.

**Comment by JuanjiJG** [comment]
Hi @hafeezy2j , and Happy New Year for you too!

Regarding your question, we still can't guarantee at a 100% that the upgrading process will be perfect. We still need some time to investigate about that log messages.

But for now, I think that the logs are just temporary and they don't have to mean the upgrading process failed by some reason. If you followed our [upgrading guide](https://documentation.wazuh.com/current/installation-guide/upgrading/index.html) and after that you can access the new Kibana interface with no problems, you can see your alerts in our Wazuh App and the new alerts are showing, then there's no reason to think there's any kind of problem.

I understand your worries about this, and if you want, you can wait some more time, so we can assure everything will be working fine.

If you still got more questions or problems, feel free to ask again and we'll try to help you. Thanks for your patience.

Best regards,
Juanjo

**Comment by hafeezy2j** [comment]
Hello @JuanjiJG and @havidarou 

I'm following [wazuh upgrading-different-major guide](https://documentation.wazuh.com/current/installation-guide/upgrading/different_major.html#upgrading-different-major)  to upgrade Elasticstack on our production environment and I'm  unable to start the elasticsearch service once I upgrade from version 5.6.7 to 6.1.1 

● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/elasticsearch.service.d
           └─elasticsearch.conf
   Active: failed (Result: exit-code) since Fri 2018-02-02 09:36:37 EST; 2s ago
     Docs: http://www.elastic.co
  Process: 3085 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p ${PID_DIR}/elasticsearch.pid --quiet (code=exited, status=1/FAILURE)
 Main PID: 3085 (code=exited, status=1/FAILURE)

Feb 02 09:36:37 mtc-wazuh-XXX.XXXX.local elasticsearch[3085]: 2018-02-02 09:36:37,204 main ERROR Null object returned for RollingFile in Appenders.
Feb 02 09:36:37 mtc-wazuh-XXX.XXXX.local elasticsearch[3085]: 2018-02-02 09:36:37,204 main ERROR Null object returned for RollingFile in Appenders.
Feb 02 09:36:37 mtc-wazuh-XXX.XXXX.local elasticsearch[3085]: 2018-02-02 09:36:37,209 main ERROR Null object returned for RollingFile in Appenders.
Feb 02 09:36:37 mtc-wazuh-XXX.XXXX.local elasticsearch[3085]: 2018-02-02 09:36:37,210 main ERROR Unable to locate appender "rolling" for logger config "root"
Feb 02 09:36:37 mtc-wazuh-XXX.XXXX.local elasticsearch[3085]: 2018-02-02 09:36:37,210 main ERROR Unable to locate appender "index_indexing_slowlog_rolling" for logger config "index.indexing.slowlog.index"
Feb 02 09:36:37 mtc-wazuh-XXX.XXXX.local elasticsearch[3085]: 2018-02-02 09:36:37,210 main ERROR Unable to locate appender "index_search_slowlog_rolling" for logger config "index.search.slowlog"
Feb 02 09:36:37 mtc-wazuh-XXX.XXXX.local elasticsearch[3085]: 2018-02-02 09:36:37,211 main ERROR Unable to locate appender "deprecation_rolling" for logger config "org.elasticsearch.deprecation"
Feb 02 09:36:37 mtc-wazuh-XXX.XXXX.local systemd[1]: elasticsearch.service: main process exited, code=exited, status=1/FAILURE
Feb 02 09:36:37 mtc-wazuh-XXX.XXXX.local systemd[1]: Unit elasticsearch.service entered failed state.
Feb 02 09:36:37 mtc-wazuh-XXX.XXXX.local systemd[1]: elasticsearch.service failed.

Here are tail logs from /var/log/elasticsearch/elasticsearch.log

2018-02-02T08:24:52,030][INFO ][o.e.n.Node               ] [NhaBLZ4] stopped
[2018-02-02T08:24:52,030][INFO ][o.e.n.Node               ] [NhaBLZ4] closing ...
[2018-02-02T08:24:52,045][INFO ][o.e.n.Node               ] [NhaBLZ4] closed
[2018-02-02T09:16:32,000][INFO ][o.e.n.Node               ] [] initializing ...
[2018-02-02T09:16:32,495][INFO ][o.e.e.NodeEnvironment    ] [NhaBLZ4] using [1] data paths, mounts [[/ (rootfs)]], net usable_space [85.1gb], net total_space [144gb], spins? [unknown], types [rootfs]
[2018-02-02T09:16:32,495][INFO ][o.e.e.NodeEnvironment    ] [NhaBLZ4] heap size [5.9gb], compressed ordinary object pointers [true]
[2018-02-02T09:17:49,059][INFO ][o.e.n.Node               ] node name [NhaBLZ4] derived from node ID [NhaBLZ4CRfmOuSDTa2Y0_A]; set [node.name] to override
[2018-02-02T09:17:49,060][INFO ][o.e.n.Node               ] version[5.6.7], pid[1181], build[4669214/2018-01-25T21:14:50.776Z], OS[Linux/3.10.0-693.17.1.el7.x86_64/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_144/25.144-b01]
[2018-02-02T09:17:49,060][INFO ][o.e.n.Node               ] JVM arguments [-Xms6g, -Xmx6g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/usr/share/elasticsearch]
[2018-02-02T09:17:51,218][INFO ][o.e.p.PluginsService     ] [NhaBLZ4] loaded module [aggs-matrix-stats]
[2018-02-02T09:17:51,218][INFO ][o.e.p.PluginsService     ] [NhaBLZ4] loaded module [ingest-common]
[2018-02-02T09:17:51,218][INFO ][o.e.p.PluginsService     ] [NhaBLZ4] loaded module [lang-expression]
[2018-02-02T09:17:51,218][INFO ][o.e.p.PluginsService     ] [NhaBLZ4] loaded module [lang-groovy]
[2018-02-02T09:17:51,218][INFO ][o.e.p.PluginsService     ] [NhaBLZ4] loaded module [lang-mustache]
[2018-02-02T09:17:51,219][INFO ][o.e.p.PluginsService     ] [NhaBLZ4] loaded module [lang-painless]
[2018-02-02T09:17:51,219][INFO ][o.e.p.PluginsService     ] [NhaBLZ4] loaded module [parent-join]
[2018-02-02T09:17:51,219][INFO ][o.e.p.PluginsService     ] [NhaBLZ4] loaded module [percolator]
[2018-02-02T09:17:51,219][INFO ][o.e.p.PluginsService     ] [NhaBLZ4] loaded module [reindex]
[2018-02-02T09:17:51,219][INFO ][o.e.p.PluginsService     ] [NhaBLZ4] loaded module [transport-netty3]
[2018-02-02T09:17:51,219][INFO ][o.e.p.PluginsService     ] [NhaBLZ4] loaded module [transport-netty4]
[2018-02-02T09:17:51,220][INFO ][o.e.p.PluginsService     ] [NhaBLZ4] no plugins loaded
[2018-02-02T09:17:53,814][INFO ][o.e.d.DiscoveryModule    ] [NhaBLZ4] using discovery type [zen]
[2018-02-02T09:18:00,810][INFO ][o.e.n.Node               ] initialized
[2018-02-02T09:18:00,810][INFO ][o.e.n.Node               ] [NhaBLZ4] starting ...
[2018-02-02T09:18:01,017][INFO ][o.e.t.TransportService   ] [NhaBLZ4] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
[2018-02-02T09:18:04,109][INFO ][o.e.c.s.ClusterService   ] [NhaBLZ4] new_master {NhaBLZ4}{NhaBLZ4CRfmOuSDTa2Y0_A}{1qP0yKFZTMKX41GHFX7auw}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2018-02-02T09:18:04,138][INFO ][o.e.h.n.Netty4HttpServerTransport] [NhaBLZ4] publish_address {127.0.0.1:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}
[2018-02-02T09:18:04,138][INFO ][o.e.n.Node               ] [NhaBLZ4] started
[2018-02-02T09:19:30,785][INFO ][o.e.g.GatewayService     ] [NhaBLZ4] recovered [199] indices into cluster_state
[2018-02-02T09:19:30,785][WARN ][o.e.c.s.ClusterService   ] [NhaBLZ4] cluster state update task [local-gateway-elected-state] took [1.4m] above the warn threshold of 30s
[2018-02-02T09:28:45,872][INFO ][o.e.n.Node               ] [NhaBLZ4] stopping ...
[2018-02-02T09:28:47,976][INFO ][o.e.n.Node               ] [NhaBLZ4] stopped
[2018-02-02T09:28:47,978][INFO ][o.e.n.Node               ] [NhaBLZ4] closing ...
[2018-02-02T09:28:47,992][INFO ][o.e.n.Node               ] [NhaBLZ4] closed

Am i missing something here?

Thanks,
Hafeez

**Comment by havidarou** [comment]
Hi @hafeezy2j ,

I've never seen those errors.

They seem related to your elasticsearch installation, have you got some kind of index rolling process in there?

Regards.

**Comment by hafeezy2j** [comment]
Hello @havidarou,

No I dont.  if I uninstall elasticsearch and install the 6.1.1 version, I dont see these errors. dont know if doing so will cause any issues for the rest of upgrade process..

Thanks,

**Comment by havidarou** [comment]
Hi @hafeezy2j ,

it shouldn't cause errors, but still, it is pretty weird.

Can you elaborate a bit on your architecture? Maybe I can reproduce it.

I would also recommend you to post in elasticsearch forums/github to see if they can help you in that regard.

Regards.

**Comment by hafeezy2j** [comment]
Hello @havidarou,

I have a simple setup. running wazuh in distributed setup where I have one wazuh manager and one elasticstack running followings...

elasticsearch 5.6.5
kibana 5.6.5
wazuh-api 2.1.1

When I [Upgrade Elasticsearch](https://documentation.wazuh.com/current/installation-guide/upgrading/different_major.html#upgrading-different-major)  by issuing  yum install elasticsearch-6.1.3 command, everything goes well but I'm unable to start elasticsearch service. 

Here are the errors I see when I do systemctl status elasticsearch.service

 elasticsearch.service - Elasticsearch
Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: disabled)
Drop-In: /etc/systemd/system/elasticsearch.service.d
└─elasticsearch.conf
Active: failed (Result: exit-code) since Fri 2018-02-02 09:36:37 EST; 2s ago
Docs: http://www.elastic.co
Process: 3085 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p ${PID_DIR}/elasticsearch.pid --quiet (code=exited, status=1/FAILURE)
Main PID: 3085 (code=exited, status=1/FAILURE)

Feb 02 09:36:37 mtc-wazuh-XXX.XXXX.local elasticsearch[3085]: 2018-02-02 09:36:37,204 main ERROR Null object returned for RollingFile in Appenders.
Feb 02 09:36:37 mtc-wazuh-XXX.XXXX.local elasticsearch[3085]: 2018-02-02 09:36:37,204 main ERROR Null object returned for RollingFile in Appenders.
Feb 02 09:36:37 mtc-wazuh-XXX.XXXX.local elasticsearch[3085]: 2018-02-02 09:36:37,209 main ERROR Null object returned for RollingFile in Appenders.
Feb 02 09:36:37 mtc-wazuh-XXX.XXXX.local elasticsearch[3085]: 2018-02-02 09:36:37,210 main ERROR Unable to locate appender "rolling" for logger config "root"
Feb 02 09:36:37 mtc-wazuh-XXX.XXXX.local elasticsearch[3085]: 2018-02-02 09:36:37,210 main ERROR Unable to locate appender "index_indexing_slowlog_rolling" for logger config "index.indexing.slowlog.index"
Feb 02 09:36:37 mtc-wazuh-XXX.XXXX.local elasticsearch[3085]: 2018-02-02 09:36:37,210 main ERROR Unable to locate appender "index_search_slowlog_rolling" for logger config "index.search.slowlog"
Feb 02 09:36:37 mtc-wazuh-XXX.XXXX.local elasticsearch[3085]: 2018-02-02 09:36:37,211 main ERROR Unable to locate appender "deprecation_rolling" for logger config "org.elasticsearch.deprecation"
Feb 02 09:36:37 mtc-wazuh-XXX.XXXX.local systemd[1]: elasticsearch.service: main process exited, code=exited, status=1/FAILURE
Feb 02 09:36:37 mtc-wazuh-XXX.XXXX.local systemd[1]: Unit elasticsearch.service entered failed state.
Feb 02 09:36:37 mtc-wazuh-XXX.XXXX.local systemd[1]: elasticsearch.service failed.

Here are tail logs from /var/log/elasticsearch/elasticsearch.log

2018-02-02T08:24:52,030][INFO ][o.e.n.Node ] [NhaBLZ4] stopped
[2018-02-02T08:24:52,030][INFO ][o.e.n.Node ] [NhaBLZ4] closing ...
[2018-02-02T08:24:52,045][INFO ][o.e.n.Node ] [NhaBLZ4] closed
[2018-02-02T09:16:32,000][INFO ][o.e.n.Node ] [] initializing ...
[2018-02-02T09:16:32,495][INFO ][o.e.e.NodeEnvironment ] [NhaBLZ4] using [1] data paths, mounts [[/ (rootfs)]], net usable_space [85.1gb], net total_space [144gb], spins? [unknown], types [rootfs]
[2018-02-02T09:16:32,495][INFO ][o.e.e.NodeEnvironment ] [NhaBLZ4] heap size [5.9gb], compressed ordinary object pointers [true]
[2018-02-02T09:17:49,059][INFO ][o.e.n.Node ] node name [NhaBLZ4] derived from node ID [NhaBLZ4CRfmOuSDTa2Y0_A]; set [node.name] to override
[2018-02-02T09:17:49,060][INFO ][o.e.n.Node ] version[5.6.7], pid[1181], build[4669214/2018-01-25T21:14:50.776Z], OS[Linux/3.10.0-693.17.1.el7.x86_64/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_144/25.144-b01]
[2018-02-02T09:17:49,060][INFO ][o.e.n.Node ] JVM arguments [-Xms6g, -Xmx6g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/usr/share/elasticsearch]
[2018-02-02T09:17:51,218][INFO ][o.e.p.PluginsService ] [NhaBLZ4] loaded module [aggs-matrix-stats]
[2018-02-02T09:17:51,218][INFO ][o.e.p.PluginsService ] [NhaBLZ4] loaded module [ingest-common]
[2018-02-02T09:17:51,218][INFO ][o.e.p.PluginsService ] [NhaBLZ4] loaded module [lang-expression]
[2018-02-02T09:17:51,218][INFO ][o.e.p.PluginsService ] [NhaBLZ4] loaded module [lang-groovy]
[2018-02-02T09:17:51,218][INFO ][o.e.p.PluginsService ] [NhaBLZ4] loaded module [lang-mustache]
[2018-02-02T09:17:51,219][INFO ][o.e.p.PluginsService ] [NhaBLZ4] loaded module [lang-painless]
[2018-02-02T09:17:51,219][INFO ][o.e.p.PluginsService ] [NhaBLZ4] loaded module [parent-join]
[2018-02-02T09:17:51,219][INFO ][o.e.p.PluginsService ] [NhaBLZ4] loaded module [percolator]
[2018-02-02T09:17:51,219][INFO ][o.e.p.PluginsService ] [NhaBLZ4] loaded module [reindex]
[2018-02-02T09:17:51,219][INFO ][o.e.p.PluginsService ] [NhaBLZ4] loaded module [transport-netty3]
[2018-02-02T09:17:51,219][INFO ][o.e.p.PluginsService ] [NhaBLZ4] loaded module [transport-netty4]
[2018-02-02T09:17:51,220][INFO ][o.e.p.PluginsService ] [NhaBLZ4] no plugins loaded
[2018-02-02T09:17:53,814][INFO ][o.e.d.DiscoveryModule ] [NhaBLZ4] using discovery type [zen]
[2018-02-02T09:18:00,810][INFO ][o.e.n.Node ] initialized
[2018-02-02T09:18:00,810][INFO ][o.e.n.Node ] [NhaBLZ4] starting ...
[2018-02-02T09:18:01,017][INFO ][o.e.t.TransportService ] [NhaBLZ4] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
[2018-02-02T09:18:04,109][INFO ][o.e.c.s.ClusterService ] [NhaBLZ4] new_master {NhaBLZ4}{NhaBLZ4CRfmOuSDTa2Y0_A}{1qP0yKFZTMKX41GHFX7auw}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2018-02-02T09:18:04,138][INFO ][o.e.h.n.Netty4HttpServerTransport] [NhaBLZ4] publish_address {127.0.0.1:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}
[2018-02-02T09:18:04,138][INFO ][o.e.n.Node ] [NhaBLZ4] started
[2018-02-02T09:19:30,785][INFO ][o.e.g.GatewayService ] [NhaBLZ4] recovered [199] indices into cluster_state
[2018-02-02T09:19:30,785][WARN ][o.e.c.s.ClusterService ] [NhaBLZ4] cluster state update task [local-gateway-elected-state] took [1.4m] above the warn threshold of 30s
[2018-02-02T09:28:45,872][INFO ][o.e.n.Node ] [NhaBLZ4] stopping ...
[2018-02-02T09:28:47,976][INFO ][o.e.n.Node ] [NhaBLZ4] stopped
[2018-02-02T09:28:47,978][INFO ][o.e.n.Node ] [NhaBLZ4] closing ...
[2018-02-02T09:28:47,992][INFO ][o.e.n.Node ] [NhaBLZ4] closed

Thanks,
Hafeez

**Comment by JuanjiJG** [comment]
Hi again @hafeezy2j,

I've been reading about the errors you're getting. Since you've performed an upgrade, maybe you have to reload the services and enable again the Elasticsearch service. Please try the following commands (as superuser):
`systemctl daemon-reload`
`systemctl enable elasticsearch`
`systemctl start elasticsearch`

Some of the errors you're getting may be related to a problem reading the installation paths, and sometimes the previous commands would help to solve this.

Also, check your Elasticsearch configuration file (usually located at `/etc/elasticsearch/elasticsearch.yml`), since the upgrade may have deprecated or change some Elastic 5 configuration options.

In addition to our help, we strongly recommend you to go to the [Elastic forums](https://discuss.elastic.co/) and open a new thread describing your problem. Maybe they will have more knowledge regarding your issue.

Thanks for your patience.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Hi @hafeezy2j, I'm going to close this issue due to inactivity. Don't hesitate on open a new issue if you are facing any kind of trouble, have a nice day.

Best regards,
Jesús
