### ISSUE TITLE
Kibana does not start after installing the app

### ISSUE THREAD

**Issue by a108a108** [wazuh/wazuh-kibana-app#2040]
Hello, 
i installed the wazuh app for kibana 7.5.2 and when i do restart on the kibana daemon it never loads.
Kibana stays on "Kibana server is not ready yet". There are no errors in the journal or anything that i can relate to the problem.  

Cent os 7.7

**Comment by Joanes04** [comment]
Hi @a108a108,

We're going to run some checks to locate the problem. Please follow the steps below:

- Let's start by restarting Elasticsearch and Kibana:

`sudo systemctl restart elasticsearch.service`
`sudo systemctl restart kibana.service`

- After some minutes, and if it’s still failing, check if Elasticsearch is running without  errors. Could you please send us the output of these commands?

`sudo journalctl -u elasticsearch.service`
`sudo systemctl status -l  elasticsearch.service`

> The same for Kibana:

`sudo journalctl -u kibana.service > output.txt` ( Please attach the file output.txt)
`sudo systemctl status -l kibana.service`

- Finally, let's check the status of Filebeat:

`sudo systemctl status filebeat.service`
`sudo filebeat test output`


Best regards,
Alberto

**Comment by a108a108** [comment]
Hi @Joanes04 ,
thanks for your response, I am attaching a file with the logs.
Btw i want to use in distributed architecture so filebeat is not on the same machine with kibana and es.
Also when kibana is on state it continuously eats ram. 

[output.txt](https://github.com/wazuh/wazuh-kibana-app/files/4137448/output.txt)

**Comment by Joanes04** [comment]
Hi @a108a108,

There seems to be a problem in elasticsearch:

```
[2020-01-31T05:04:50,996][WARN ][r.suppressed             ] [localhost] path: /.kibana_task_manager/_count, params: {index=.kibana_task_manager}
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:534) [elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:305) [elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:563) [elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:384) [elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.lambda$performPhaseOnShard$0(AbstractSearchAsyncAction.java:219) [elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction$2.doRun(AbstractSearchAsyncAction.java:284) [elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) [elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773) [elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.5.2.jar:7.5.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]

```
Please, run the following queries to the Elasticsearch API so we can have more information to help you with this issue:

- curl -XGET 'http://localhost:9200/_cluster/health?pretty'
- curl -XGET 'http://localhost:9200/_cat/nodes?v&s=name:asc'
- curl -XGET "http://localhost:9200/_cat/allocation?v&s=node"
- curl -XGET "http://localhost:9200/_cat/shards?v&h=i,s,p,st,d,sto,ip,node,ur,ua,cs&s=st:desc" | grep -i unassig
- curl -XGET 'http://localhost:9200/_cat/indices?v&s=index:asc'

Best regards,
Alberto

**Comment by a108a108** [comment]
Hi,
it was a low ram issue, after bumping it up a little it started.

**Comment by Joanes04** [comment]
Hello @a108a108 ,

I'm glad it worked out. Any other questions please feel free to open another issue, or contact us via [google groups](https://groups.google.com/forum/#!forum/wazuh) or our [slack](wazuh.slack.com) channel.

Best regards,
Alberto
