### ISSUE TITLE
Node unable to start and causing wazuh not functioning.

### ISSUE THREAD

**Issue by lukelee1987** [wazuh/wazuh-kibana-app#2455]
| Wazuh | Elastic | Rev |
| 3.12 | 7.7 | --- |
| 3.x   | 6.x     | 444 |

**Description**
After awhile (3- 4 weeks) Wazuh unable to start. 
**Steps to reproduce**

**Screenshots**
```
root@eta10:/var/ossec/bin# node app.js stop
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/var/ossec/bin/app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

**Comment by AdriiiPRodri** [comment]
Hi lukelee1987,

Probably this error is due to a problem with the path of the **app.js** file. This file is part of the Wazuh API and if it is not active Kibana will not be able to work properly.

To fix this problem, let's change the path to: `var/ossec/api` (this is the current Wazuh API path) so that our command would look like this:

`cd /var/ossec/api`
`/var/ossec/api# node app.js start|stop|restart`

In addition, we can also use the API service to do this:

`service wazuh-api start|stop|restart` or `systemctl start|stop|restart wazuh-api`

I hope I helped you with your problem, if you have any other questions, don't hesitate to ask.

Best regards,
Adrián Peña

**Comment by lukelee1987** [comment]
Hi thanks for replying.

Ya, i have tested and run the commands. but the API  and WAZUH still dont
run properly.

Best Regards,
*Luke Lee*
System Analyst (Digital System Security)
Contact: (S'pore)+65 92985349

**Comment by AdriiiPRodri** [comment]
You're welcome,

In order to help you better, please share with us the output of the `node app.js restart` command inside `/var/ossec/api` path. 

On the other hand, let's do the same with the command `service wazuh-manager restart`. If either or both of them fail, could you execute the following command `tail -n50 /var/ossec/logs/api.log` or `tail -n50 /var/ossec/logs/ossec.log` (depending on which one fails) and show the output? This way we can see where the error is.

Regards

**Comment by lukelee1987** [comment]
Hi this is the error from `node app.js restart `

```
internal/modules/cjs/loader.js:583
    throw err;
    ^
Error: Cannot find module '/etc/heartbeat/monitors.d/app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

App.js
```
#!/usr/bin/env node
  2
  3 /**
  4  * Wazuh API RESTful
  5  * Copyright (C) 2015-2020 Wazuh, Inc.  All rights reserved.
  6  * Wazuh.com
  7  *
  8  * This program is a free software; you can redistribute it
  9  * and/or modify it under the terms of the GNU General Public
 10  * License (version 2) as published by the FSF - Free Software
 11  * Foundation.
 12  */
 13
 14 if (process.getuid() !== 0){
 15     console.log('A root user is required to start the API.');
 16     process.exit(1);
 17 }
 18
 19 /********************************************/
 20 /* Root actions
 21 /********************************************/
 22 try {
 23     var auth = require("http-auth");
 24 } catch (e) {
 25     console.log("Dependencies not found. Try 'npm install' in /var/ossec/api. Exiting...");
 26     process.exit(1);
 27 }
 28
 29 const check = require('./helpers/check');
 30
 31 //  Get configuration
 32 config = require('./configuration/config');
 33 if (check.configuration_file() < 0) {
 34     setTimeout(function(){ process.exit(1); }, 500);
 35     return;
 36 }
 37
 38 //  Get credentials
 39 if (config.basic_auth.toLowerCase() == "yes"){
 40     var auth_secure = auth.basic({
 41         realm: "OSSEC API",
 42         file: __dirname + "/configuration/auth/user"
 43     });
 44 }
46 //  Get Certs
 47 var options = {};
 48
 49 var fs = require('fs');
 50 if (config.https.toLowerCase() == "yes"){
 51     var api_route = config.ossec_path + '/api/';
 52     var option_paths = {};
 53
 54     // Cert and key
 55     option_paths.key = config.https_key || 'configuration/ssl/server.key';
 56     if (option_paths.key.charAt(0) != '/'){
 57         option_paths.key = api_route + option_paths.key;
 58     }
 59
 60     option_paths.cert = config.https_cert  || 'configuration/ssl/server.crt';
 61     if (option_paths.cert.charAt(0) != '/'){
 62         option_paths.cert = api_route + option_paths.cert;
 63     }
 64
 65     options.key = fs.readFileSync(option_paths.key);
 66     options.cert = fs.readFileSync(option_paths.cert);
 67
 68     // CA
 69     var use_ca = config.https_use_ca || 'no';
 70     if (use_ca.toLowerCase() == "yes"){
 71         option_paths.ca = config.https_ca || 'configuration/ssl/ca.crt';
 72         if (option_paths.ca.charAt(0) != '/'){
 73             option_paths.ca = api_route + option_paths.ca;
 74         }
 75
 76         options.ca = fs.readFileSync(option_paths.ca);
 77     }
 78     if (config.secureProtocol && config.secureProtocol != "") options.secureProtocol = config.secureProtocol;
 79     if (config.ciphers && config.ciphers != "") options.ciphers = config.ciphers;
 80     if (config.honorCipherOrder) options.honorCipherOrder = config.honorCipherOrder;
 81     if (config.secureOptions) options.secureOptions = config.secureOptions;
 82 }
 85 /********************************************/
 86 /* Drop privileges
 87 /********************************************/
 88 if (config.drop_privileges || config.drop_privileges == undefined) {
 89     try {
 90         process.setgid('ossec');
 91         process.setuid('ossec');
 92     } catch(err) {
 93         console.log('Drop privileges failed: ' + err.message);
 94         process.exit(1);
 95     }
 96 }
 97
 98 /********************************************/
 99 /* Modules, vars and global vars
100 /********************************************/
101 try {
102     var express = require('express');
103     var bodyParser = require('body-parser');
104     var cors = require('cors')
105     var moment = require('moment');
106     res_h = require('./helpers/response_handler');
107     logger = require('./helpers/logger');
108 } catch (e) {
109     console.log("Dependencies not found. Try 'npm install' in /var/ossec/api. Exiting...");
110     process.exit(1);
111 }
112
113 api_path = __dirname;
114 python_bin = config.ossec_path + '/framework/python/bin/python3';
115
116 /********************************************/
117 /* Config APP
118 /********************************************/
119 info_package = require('./package.json');
120 var version_mmp = info_package.version.split('.'); // major.minor.patch
121 var current_mm_version = version_mmp[0] + '.' + version_mmp[1]; // major.minor
123 if (process.argv.length == 3 && process.argv[2] == "-f")
124     logger.set_foreground();
125
126 if (check.wazuh(logger) < 0) {
127     setTimeout(function(){ process.exit(1); }, 500);
128     return;
129 }
130
131 var port = process.env.PORT || config.port;
132
133 if (config.host != "0.0.0.0")
134     var host = config.host;
135
136 var app = express();
137
138 // CORS
139 if (config.cors.toLowerCase() == "yes"){
140     app.use(cors());
141 }
142
143 // Basic authentication
144 if (config.basic_auth.toLowerCase() == "yes"){
145     app.use(auth.connect(auth_secure));
146
147     auth_secure.on('fail', (result, req) => {
148         logger.set_user(result.user);
149         var log_msg = "[" + req.connection.remoteAddress + "] " + "User: \"" + result.user + "\" - Authentication failed.";
150         logger.log(log_msg);
151     });
152
153     auth_secure.on('error', (error, req) => {
154         logger.set_user("");
155         var log_msg = "[" + req.connection.remoteAddress + "] Authentication error: " + error.code + " - " + error.message;
156         logger.log(log_msg);
157     });
158 }
159
160 // temporary
161 if (config.ld_library_path) {
162     logger.warning("LD library path configuration is deprecated.");
163 }
164 if (config.python) {
165     logger.warning("Python configuration is deprecated. Using " + python_bin);
169 // Body
170 app.use(bodyParser.json());
171 app.use(bodyParser.urlencoded({extended: true}));
172 app.use(bodyParser.text({type:"application/xml", limit:"1mb"}));
173 app.use(bodyParser.raw({type:"application/octet-stream", limit:"1mb"}));
174
175
176 /**
177  * Check Wazuh app version
178  * Using: Header: "wazuh-app-version: X.Y.Z"
179  */
180 app.use(function(req, res, next) {
181     var go_next = true;
182     var app_version_header = req.get('wazuh-app-version');
183     var regex_version = /^\d+\.\d+\.\d+$/i;
184
185     if (typeof app_version_header != 'undefined'){
186         if (!regex_version.test(app_version_header)){
187             go_next = false;
188             res_h.bad_request(req, res, 801);
189         }
190         else{
191             var app_version_mmp = app_version_header.split('.'); // major.minor.patch
192             var app_mm_version = app_version_mmp[0] + '.' + app_version_mmp[1]; // major.minor
193
194             if (app_mm_version != current_mm_version){
195                 go_next = false;
196                 res_h.bad_request(req, res, 802, "Expected version '" + current_mm_version + ".x', and found '" + app_mm_version + ".x'.");
197             }
198         }
199     }
200
201     if (go_next)
202         next();
203 });
204
205 // Controllers
206 app.use("/", require('./controllers'));
207
208 // APP Errors
209 app.use (function (err, req, res, next){
210
211     if ( err == "Error: invalid json" ){
212         logger.debug(req.connection.remoteAddress + " " + req.method + " " + req.path);
222         res_h.bad_request(req, res, 701);
223     }
224     else{
225         logger.log("Internal Error");
226         if(err.stack)
227             logger.log(err.stack);
228         logger.log("Exiting...");
229         setTimeout(function(){ process.exit(1); }, 500);
230     }
231 });
232
233 /********************************************/
234 /* Create server
235 /********************************************/
236 if (config.https.toLowerCase() == "yes"){
237     var https = require('https');
238     var server = https.createServer(options, app).listen(port, host, function(){
239         logger.log("Listening on: https://" + server.address().address + ":" + port);
240     });
241 }
242 else{
243     var http = require('http');
244     var server = http.createServer(app).listen(port, host, function(){
245         logger.log("Listening on: http://" + server.address().address + ":" + port);
246     });
247 }
248
249 /********************************************/
250 /* Event handler
251 /********************************************/
252 process.on('uncaughtException', function(err) {
253
254     if (err.errno == "EADDRINUSE")
255         logger.log("Error: Address in use (port " + port + "): Close the program using that port or change the port.")
256     else {
257       logger.log("Internal Error: uncaughtException");
258       if(err.stack)
259           logger.log(err.stack);
260     }
261
262     logger.log("Exiting...");
263     setTimeout(function(){ process.exit(1); }, 500);
264 });
266 process.on('SIGTERM', function() {
267     logger.log("Exiting... (SIGTERM)");
268     setTimeout(function(){ process.exit(1); }, 500);
269 });
270
271 process.on('SIGINT', function() {
272     logger.log("Exiting... (SIGINT)");
273     setTimeout(function(){ process.exit(1); }, 500);
274 });
```

API Logs:
```
WazuhAPI 2020-09-07 16:30:02 elastic: [10.0.106.144] GET /cluster/status? - 200 - error: '1017'.
WazuhAPI 2020-09-07 16:45:00 elastic: [10.0.106.144] GET /agents/?offset=0&limit=1&q=id!%3D000 - 200 - error: '1017'.
WazuhAPI 2020-09-07 16:45:01 elastic: [10.0.106.144] GET /cluster/status? - 200 - error: '1017'.
WazuhAPI 2020-09-07 17:00:01 elastic: [10.0.106.144] GET /agents/?offset=0&limit=1&q=id!%3D000 - 200 - error: '1017'.
WazuhAPI 2020-09-07 17:00:01 elastic: [10.0.106.144] GET /cluster/status? - 200 - error: '1017'.
WazuhAPI 2020-09-07 17:15:00 elastic: [10.0.106.144] GET /agents/?offset=0&limit=1&q=id!%3D000 - 200 - error: '1017'.
WazuhAPI 2020-09-07 17:15:01 elastic: [10.0.106.144] GET /cluster/status? - 200 - error: '1017'.
WazuhAPI 2020-09-07 17:30:02 elastic: [10.0.106.144] GET /agents/?offset=0&limit=1&q=id!%3D000 - 200 - error: '1017'.
WazuhAPI 2020-09-07 17:30:02 elastic: [10.0.106.144] GET /cluster/status? - 200 - error: '1017'.
WazuhAPI 2020-09-07 17:45:00 elastic: [10.0.106.144] GET /agents/?offset=0&limit=1&q=id!%3D000 - 200 - error: '1017'.
WazuhAPI 2020-09-07 17:45:01 elastic: [10.0.106.144] GET /cluster/status? - 200 - error: '1017'.

```

Oseec.log was some old issues on the Authentication Issue:
```
2020/09/07 17:58:29 ossec-syscheckd[39557] fim_db.c:472 at fim_db_check_transaction(): DEBUG: Database transaction completed.
2020/09/07 17:58:29 ossec-remoted[39571] secure.c:349 at HandleSecureMessage(): WARNING: (1213): Message from '10.0.106.84' not allowed. Cannot find the ID of the agent. Source agent ID is unknown.
2020/09/07 17:58:29 ossec-remoted[39571] secure.c:349 at HandleSecureMessage(): WARNING: (1213): Message from '10.0.106.63' not allowed. Cannot find the ID of the agent. Source agent ID is unknown.
2020/09/07 17:58:29 ossec-remoted[39571] msgs.c:311 at ReadSecMSG(): WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '127' at 'any'.
2020/09/07 17:58:29 ossec-remoted[39571] secure.c:334 at HandleSecureMessage(): WARNING: (1408): Invalid ID 118 for the source ip: '10.4.12.208' (name 'DGXV4').
2020/09/07 17:58:29 ossec-remoted[39571] msgs.c:311 at ReadSecMSG(): WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '146' at 'any'.
2020/09/07 17:58:30 ossec-remoted[39571] msgs.c:311 at ReadSecMSG(): WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '121' at 'any'.
2020/09/07 17:58:30 ossec-remoted[39571] msgs.c:311 at ReadSecMSG(): WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '124' at 'any'.
2020/09/07 17:58:30 ossec-remoted[39571] secure.c:334 at HandleSecureMessage(): WARNING: (1408): Invalid ID 111 for the source ip: '10.20.3.195' (name 'THETA').
2020/09/07 17:58:31 ossec-syscheckd[39557] fim_db.c:472 at fim_db_check_transaction(): DEBUG: Database transaction completed.
2020/09/07 17:58:31 ossec-remoted[39571] msgs.c:311 at ReadSecMSG(): WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '122' at 'any'.
2020/09/07 17:58:31 ossec-remoted[39571] msgs.c:311 at ReadSecMSG(): WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '108' at '10.0.109.47'.
2020/09/07 17:58:32 ossec-remoted[39571] msgs.c:311 at ReadSecMSG(): WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '095' at '10.0.106.118'.
2020/09/07 17:58:32 ossec-remoted[39571] secure.c:334 at HandleSecureMessage(): WARNING: (1408): Invalid ID 112 for the source ip: '10.20.3.103' (name 'THETA1').
2020/09/07 17:58:33 ossec-syscheckd[39557] fim_db.c:472 at fim_db_check_transaction(): DEBUG: Database transaction completed.
2020/09/07 17:58:33 ossec-remoted[39571] secure.c:349 at HandleSecureMessage(): WARNING: (1213): Message from '10.0.106.62' not allowed. Cannot find the ID of the agent. Source agent ID is unknown.

```

**Comment by AdriiiPRodri** [comment]
Hi lukelee1987,

Error 1017 occurs when one or more Wazuh essential daemons are stopped, in a state of failure or restarting. The first thing we'll do to fix this is running the following command `service wazuh-manager restart`.

Taking a look at the API log, we could determine that it is working correctly. Reviewing my previous message I saw that the command I gave you was not correct. To start the API using the file '**/var/ossec/api/app.js**' you need to run this command: `node /var/ossec/api/app.js &`. Although we recommend using the `service wazuh-api start|stop|restart` command. After this we will test the functioning of it by doing a request.

In case it doesn't work, the next thing we'll do is execute this command: `ps -edf | grep '/var/ossec'` with it we'll be able to see if any essential daemon is missing.

After this, we are going to execute the following command to check the status of the agents `/var/ossec/bin/cluster_control -a`, this command will give us information about the connections of the agents with the manager nodes.

Finally, in order to replicate this behavior, please run the following command: `node --version`, this command will return the node version you are running.

Regards

**Comment by AdriiiPRodri** [comment]
Close this issue due to inactivity

**Comment by lukelee1987** [comment]
Hi sorry, forgot to reply. I am still facing issue. can reopen this post?

**Comment by AdriiiPRodri** [comment]
Hi @lukelee1987,

No problem, it's open now. Could you share the output of the commands in my previous comment? This way we can see what is happening and we can try to replicate the problem.

**Comment by AdriiiPRodri** [comment]
Close this issue due to inactivity
