### ISSUE TITLE
Inserting weird characters in manage agent of a group produces Wazuh manager server fall down

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-kibana-app#2881]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0   | 7.10.0     | 4101-1 |

**Description**

Hello team,

If we perform some searchs with "weard characters" in `Manage agents` in a group menu, manager fall down suddelly.

- ` /var/log/messages.log`

```
Feb  2 09:35:32 ip-172-31-36-201 kibana: {"type":"error","@timestamp":"2021-02-02T09:35:22Z","tags":[],"pid":13105,"level":"error","error":{"message":"Internal Server Error","name":"Error","stack":"Error: Internal Server Error\n    at HapiResponseAdapter.toError (/usr/share/kibana/src/core/server/http/router/response_adapter.js:132:19)\n    at HapiResponseAdapter.toHapiResponse (/usr/share/kibana/src/core/server/http/router/response_adapter.js:86:19)\n    at HapiResponseAdapter.handle (/usr/share/kibana/src/core/server/http/router/response_adapter.js:81:17)\n    at Router.handle (/usr/share/kibana/src/core/server/http/router/router.js:164:34)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":null,"query":{},"pathname":"/api/request","path":"/api/request","href":"/api/request"},"message":"Internal Server Error"}
```

- `api.log`

```
2021/02/02 09:41:02 INFO: wazuh-wui 127.0.0.1 "GET /security/user/authenticate" done in 0.258s: 200
2021/02/02 09:41:09 INFO: wazuh-wui 127.0.0.1 "GET /security/user/authenticate" done in 0.317s: 200
2021/02/02 09:41:09 INFO: wazuh-wui 127.0.0.1 "GET /security/user/authenticate" done in 0.386s: 200
2021/02/02 09:41:10 INFO: wazuh-wui 127.0.0.1 "GET /security/users/me/policies" done in 0.076s: 200
2021/02/02 09:41:12 ERROR: Timeout executing API request
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/core/cluster/dapi/dapi.py", line 250, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/core/cluster/dapi/dapi.py", line 252, in execute_local_request
    raise exception.WazuhInternalError(3021)
wazuh.core.exception.WazuhInternalError: Error 3021 - Timeout executing API request
2021/02/02 09:41:12 INFO: wazuh-wui 127.0.0.1 "GET /manager/info" done in 10.061s: 500
2021/02/02 09:41:17 ERROR: Timeout executing API request
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/core/cluster/dapi/dapi.py", line 250, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/core/cluster/dapi/dapi.py", line 252, in execute_local_request
    raise exception.WazuhInternalError(3021)
wazuh.core.exception.WazuhInternalError: Error 3021 - Timeout executing API request
2021/02/02 09:41:17 INFO: wazuh-wui 127.0.0.1 "GET /agents" done in 10.062s: 500
```

- `ossec.log `

```
`2021/02/02 09:40:14 wazuh-db: WARNING: at run_worker(): received string size is bigger than 65536 bytes
2021/02/02 09:40:35 wazuh-db: WARNING: at run_worker(): received string size is bigger than 65536 bytes
2021/02/02 09:40:36 wazuh-db: WARNING: at run_worker(): received string size is bigger than 65536 bytes
2021/02/02 09:40:36 wazuh-db: WARNING: at run_worker(): received string size is bigger than 65536 bytes
2021/02/02 09:40:48 wazuh-db: WARNING: at run_worker(): received string size is bigger than 65536 bytes
2021/02/02 09:40:55 wazuh-db: WARNING: at run_worker(): received string size is bigger than 65536 bytes
2021/02/02 09:41:00 wazuh-db: WARNING: at run_worker(): received string size is bigger than 65536 bytes
2021/02/02 09:41:02 wazuh-db: WARNING: at run_worker(): received string size is bigger than 65536 bytes`
```

**Steps to reproduce**

1. Go to `Management > Group`
2. Select one group
3. Go to `Manage agents`
4. In avaible agents search bar insert a strings with "weard characters" like 国
5. After a few requests Wazuh-manager suddely stop working an above errors appears

**Video**

https://user-images.githubusercontent.com/11089305/106583959-ee4b6780-6545-11eb-959e-6d2c6c60ae8b.mp4

**Additional context**
This happens in all browsers and systems

**Comment by BraulioV** [comment]
Hi all, 

A quick update on this issue. If we set to level 2 wazuh-db's log level, it shows the following log after running the query: [ossec.log](https://github.com/wazuh/wazuh-kibana-app/files/5910541/ossec.log)

This bug may affect the app itself, the API, and the core, specifically `wazuh-db`.
