### ISSUE TITLE
 Visualize: "field" is a required parameter

### ISSUE THREAD

**Issue by spartantri** [wazuh/wazuh-kibana-app#355]
Hi, I'm receiving a " Visualize: "field" is a required parameter" error in the Overview -> Vulnerabilities section

```
TypeError: "field" is a required parameter
    at FieldParamTypeProvider.FieldParamType.write (http://127.0.0.1:5601/bundles/commons.bundle.js?v=16573:1:1540153)
    at http://127.0.0.1:5601/bundles/commons.bundle.js?v=16573:1:317568
    at AggParams.forEach (<anonymous>)
    at AggParams.AggTypesAggParamsProvider.AggParams.write (http://127.0.0.1:5601/bundles/commons.bundle.js?v=16573:1:317526)
    at AggConfig.VisAggConfigProvider.AggConfig.write (http://127.0.0.1:5601/bundles/commons.bundle.js?v=16573:1:75241)
    at AggConfig.VisAggConfigProvider.AggConfig.toDsl (http://127.0.0.1:5601/bundles/commons.bundle.js?v=16573:1:76176)
    at http://127.0.0.1:5601/bundles/commons.bundle.js?v=16573:1:1536727
    at Array.forEach (<anonymous>)
    at AggConfigs.VisAggConfigsProvider.AggConfigs.toDsl (http://127.0.0.1:5601/bundles/commons.bundle.js?v=16573:1:1536510)
    at http://127.0.0.1:5601/bundles/commons.bundle.js?v=16573:1:588359
```

Can you tell what is the meaning?

**Comment by JuanjiJG** [comment]
Hello @spartantri,

The `Visualize: "field" is a required parameter` error is usually related to a problem between the inserted templates and the visualizations.

Do you have the same error when you open the Overview -> General tab?

I need to know some information about your current installation. Please, execute the following commands and paste here the output:
```bash
curl -XGET localhost:9200/_cat/templates?v
cat /usr/share/kibana/plugins/wazuh/package.json
```

Thanks for your patience.

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
Hello again @spartantri,

Thanks for posting your command outputs. I can see some misconfigurations in there.

In previous versions of Wazuh and the Wazuh app, it was required to insert some additional templates to the `alerts` one, and also a sample alert to properly load the fieldset. Let me guide you in order to fix this. The following steps require administrator permissions:

1. Stop Kibana and Logstash:
```bash
systemctl stop kibana
systemctl stop logstash
```

2. Insert again the necessary templates and sample alert:
```bash
curl https://raw.githubusercontent.com/wazuh/wazuh/3.2/extensions/elasticsearch/wazuh-elastic6-template-alerts.json | curl -XPUT 'http://localhost:9200/_template/wazuh' -H 'Content-Type: application/json' -d @-
curl https://raw.githubusercontent.com/wazuh/wazuh/3.2/extensions/elasticsearch/wazuh-elastic6-template-monitoring.json | curl -XPUT 'http://localhost:9200/_template/wazuh-agent' -H 'Content-Type: application/json' -d @-
curl https://raw.githubusercontent.com/wazuh/wazuh/3.2/extensions/elasticsearch/alert_sample.json | curl -XPUT "http://localhost:9200/wazuh-alerts-3.x-"`date +%Y.%m.%d`"/wazuh/sample" -H 'Content-Type: application/json' -d @-
```

3. Delete the optimizing bundles from Kibana (don't worry, they're just cache files, safe to delete):
```bash
rm -rf /usr/share/kibana/optimize/bundles
```

4. Restart Kibana and Logstash:
```bash
systemctl restart kibana
systemctl restart logstash
```

5. Wait some minutes until the optimizing bundles are re-generated and open up again the Kibana interface. Go to Management -> Index Patterns. You should see at least the `wazuh-alerts-3.x-*` and `wazuh-monitoring-3.x*` templates on the list.

6. After that, click on the `Refresh fieldset` button on the upper right corner and accept the prompted message (see attached screenshot). Now you should be able to go to the Vulnerabilities tab and see the visualizations properly loaded.
![refresh](https://user-images.githubusercontent.com/10928321/38602742-f382a394-3d6b-11e8-9101-47d64088c679.PNG)

Please let me know about the results of this. Thanks for your patience.

Regards,
Juanjo

**Comment by spartantri** [comment]
Hi Juanjo,

Thanks a lot for your support, apparently the error is gone but I noticed this other error in the elasticsearch log, may it be related to the same problem as before?

```
[2018-04-11T08:03:04,906][DEBUG][o.e.a.s.TransportSearchAction] [QXdWNEN] [wazuh-alerts-3.x-2018.04.04][1], node[QxxxxxxxxxxxxJ6V_w], [P], s[STARTED], a[id=1IiyxxxxxxxxxxxVjA]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[wazuh-alerts-3.x-*], indicesOptions=IndicesOptions[id=39, ignore_unavailable=true, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false], types=[], routing='null', preference='1523433670255', requestCache=null, scroll=null, maxConcurrentShardRequests=5, batchedReduceSize=512, preFilterShardSize=64, source={"size":0,"query":{"bool":{"must":[{"query_string":{"query":"rule.groups:\"rootcheck\"","default_field":"*","fields":[],"type":"best_fields","default_operator":"or","max_determinized_states":10000,"enable_position_increments":true,"fuzziness":"AUTO","fuzzy_prefix_length":0,"fuzzy_max_expansions":50,"phrase_slop":0,"analyze_wildcard":true,"escape":false,"auto_generate_synonyms_phrase_query":true,"fuzzy_transpositions":true,"boost":1.0}},{"match_phrase":{"manager.name":{"query":"xxxxxxxxxxx","slop":0,"boost":1.0}}},{"match_phrase":{"rule.groups":{"query":"rootcheck","slop":0,"boost":1.0}}},{"range":{"@timestamp":{"from":1523328355251,"to":1523432243517,"include_lower":true,"include_upper":true,"format":"epoch_millis","boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}},"_source":{"includes":[],"excludes":[]},"stored_fields":"*","docvalue_fields":["@timestamp","data.timestamp","data.vulnerability.published","data.vulnerability.updated","syscheck.mtime_after","syscheck.mtime_before"],"script_fields":{},"aggregations":{"2":{"terms":{"field":"agent.name","size":9999999,"min_doc_count":1,"shard_min_doc_count":0,"show_term_doc_count_error":false,"order":[{"_count":"desc"},{"_key":"asc"}]},"aggregations":{"3":{"terms":{"field":"rule.description","size":5,"min_doc_count":1,"shard_min_doc_count":0,"show_term_doc_count_error":false,"order":[{"_count":"desc"},{"_key":"asc"}]},"aggregations":{"4":{"terms":{"field":"data.title","size":5,"min_doc_count":1,"shard_min_doc_count":0,"show_term_doc_count_error":false,"order":[{"_count":"desc"},{"_key":"asc"}]}}}}}}}}}] lastShard [true]
org.elasticsearch.transport.RemoteTransportException: [QXdWNEN][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: java.lang.IllegalArgumentException: Fielddata is disabled on text fields by default. Set fielddata=true on [agent.name] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.
        at org.elasticsearch.index.mapper.TextFieldMapper$TextFieldType.fielddataBuilder(TextFieldMapper.java:301) ~[elasticsearch-6.2.1.jar:6.2.1]
        at org.elasticsearch.index.fielddata.IndexFieldDataService.getForField(IndexFieldDataService.java:115) ~[elasticsearch-6.2.1.jar:6.2.1]
        at org.elasticsearch.index.query.QueryShardContext.getForField(QueryShardContext.java:165) ~[elasticsearch-6.2.1.jar:6.2.1]
        at org.elasticsearch.search.aggregations.support.ValuesSourceConfig.resolve(ValuesSourceConfig.java:96) ~[elasticsearch-6.2.1.jar:6.2.1]
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.resolveConfig(ValuesSourceAggregationBuilder.java:294) ~[elasticsearch-6.2.1.jar:6.2.1]
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:287) ~[elasticsearch-6.2.1.jar:6.2.1]
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:36) ~[elasticsearch-6.2.1.jar:6.2.1]
        at org.elasticsearch.search.aggregations.AbstractAggregationBuilder.build(AbstractAggregationBuilder.java:132) ~[elasticsearch-6.2.1.jar:6.2.1]
        at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.build(AggregatorFactories.java:329) ~[elasticsearch-6.2.1.jar:6.2.1]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:749) ~[elasticsearch-6.2.1.jar:6.2.1]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:558) ~[elasticsearch-6.2.1.jar:6.2.1]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:534) ~[elasticsearch-6.2.1.jar:6.2.1]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:330) ~[elasticsearch-6.2.1.jar:6.2.1]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:316) [elasticsearch-6.2.1.jar:6.2.1]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:312) [elasticsearch-6.2.1.jar:6.2.1]
        at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:1002) [elasticsearch-6.2.1.jar:6.2.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:635) [elasticsearch-6.2.1.jar:6.2.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.2.1.jar:6.2.1]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) [elasticsearch-6.2.1.jar:6.2.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.2.1.jar:6.2.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

```

**Comment by JuanjiJG** [comment]
Hello again @spartantri,

If your Elastic server has already created indices before the insertion of the appropriate templates, these won't be valid for the Wazuh app, because the app expects indices with a specific type of fields, that's why we must insert the template before starting Logstash, which sends the alerts to Elasticsearch.

Your old indices will not be considered for the app, but the new ones will be generated correctly if you've inserted the template following the steps. What you can do is deleting the old ones.

List your current indices with this command:
```bash
curl -XGET localhost:9200/_cat/indices?v
```

Locate the indices starting with `wazuh-alerts-3.x-*` or `wazuh-monitoring-3.x-*` (usually followed by the year-month-day the index was created). You can delete them with this command:
```bash
curl -XDELETE localhost:9200/<index_name>?pretty
```
You can delete the old indices, the ones created before the templates insertion.

Please let me know about the results with this. If you still have questions or problems, don't hesitate to post a new comment.

Thanks for your patience.

Best regards,
Juanjo
