### ISSUE TITLE
The field "timestamp" associated with this object no longer exists in the index pattern.

### ISSUE THREAD

**Issue by sentient** [wazuh/wazuh-kibana-app#3815]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2.5   | 7.14.2    | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome|

**Description**
In the Agents result I get many errors of the following pattern.

Error: The field "timestamp" associated with this object no longer exists in the index pattern. Please use another field.
    at FieldParamType.config.write.write (https://site/42959/bundles/plugin/data/kibana/data.plugin.js:1:627309)
    at https://site/42959/bundles/plugin/data/kibana/data.plugin.js:1:455052
    at Array.forEach (<anonymous>)
    at writeParams (https://site/42959/bundles/plugin/data/kibana/data.plugin.js:1:455018)
    at AggConfig.write (https://site/42959/bundles/plugin/data/kibana/data.plugin.js:1:355081)
    at AggConfig.toDsl (https://site/42959/bundles/plugin/data/kibana/data.plugin.js:1:355960)
    at https://site/42959/bundles/plugin/data/kibana/data.plugin.js:1:190748
    at Array.forEach (<anonymous>)
    at agg_configs_AggConfigs.toDsl (https://site/42959/bundles/plugin/data/kibana/data.plugin.js:1:189329)
    at https://site/42959/bundles/plugin/wazuh/4.2.5-4206-1/wazuh.chunk.6.js:55:1397399

**Preconditions**
1. 

**Steps to reproduce**
1. Navigate to agents/<server-1>'

**Expected Result**
1. no Search Error

**Actual Result**
1. 

**Screenshots**

**Additional context**

Now it is possible that my wazuh-agent / wazuh-monitoring elastic search template are not in sync.
I have currently 3 index templates in the Legacy index templates

wazuh   wazuh-alerts-4.x-*, wazuh-archives-4.x-*
wazuh-agent  wazuh-monitoring-*
wazuh-statistics  wazuh-statistics-*

I assume I hit the wazuh-monitoring-* index

but when and how is the template set

**Comment by sentient** [comment]
filebeat was not working properly on the wazuh server 
and with that no data was sent into the elasticearch cluster, and no index data was being created.

All my vault.

It would be nice if wazuh server (or kibana app) could check on the status of filebeat like how it checks all other system help checks during startup. But that is an enhancement/feature request.

this was not a bug
