### ISSUE TITLE
Plugin is showing blank page with ChunkLoadError

### ISSUE THREAD

**Issue by yadiosl** [wazuh/wazuh-kibana-app#3915]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2.5   | 7.1.0     | 4xxx | Basic |

| Browser |
| ------- |
| Chrome|

**Description**
I upgraded my wazuh master and worker to latest 4.2.5 version, the nodes are working fine. I can see logs are coming in from wazuh agent. 
However I have the following error on the kibana wazuh plugin (version wazuh_kibana-4.2.5_7.10.2-1.zip). It show blank page for wazuh menu. I have disabled cache and tried on incognito mode as well, it is still showing blank. 
<img width="808" alt="image" src="https://user-images.githubusercontent.com/102323070/159991808-b7670c33-d252-4f48-84bd-7191c4f8d5c8.png">

Javascript console is showing the following error: 
![image](https://user-images.githubusercontent.com/102323070/159991656-cf485abf-3033-423e-a282-bfcf06fd0ef6.png)

```

/ui/favicons/manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.
/36136/bundles/plugin/wazuh/wazuh.chunk.30.js:1          Failed to load resource: the server responded with a status of 404 ()
core.entry.js:13 ChunkLoadError: Loading chunk 30 failed.
(error: https://uatkibana-sec.bc.holdings/36136/bundles/plugin/wazuh/wazuh.chunk.30.js)
    at Function.requireEnsure [as e] (/36136/bundles/plugin/wazuh/wazuh.plugin.js:1:1613)
    at _callee$ (/36136/bundles/plugin/wazuh/wazuh.plugin.js:16:8655)
    at l (/36136/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:380:982071)
    at Generator._invoke (/36136/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:380:981824)
    at Generator.forEach.e.<computed> [as next] (/36136/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:380:982428)
    at asyncGeneratorStep (/36136/bundles/plugin/wazuh/wazuh.plugin.js:16:6209)
    at _next (/36136/bundles/plugin/wazuh/wazuh.plugin.js:16:6520)
    at /36136/bundles/plugin/wazuh/wazuh.plugin.js:16:6670
    at new Promise (<anonymous>)
    at /36136/bundles/plugin/wazuh/wazuh.plugin.js:16:6432
_callee$ @ core.entry.js:13
l @ kbn-ui-shared-deps.js:380
(anonymous) @ kbn-ui-shared-deps.js:380
forEach.e.<computed> @ kbn-ui-shared-deps.js:380
asyncGeneratorStep @ core.entry.js:13
_throw @ core.entry.js:13

```
Thank you in advance, and appreciate for any potential solution for this!

**Comment by Desvelao** [comment]
Hi @yadiosl,

Could you reply to the next questions?
Q1. After updating the Wazuh plugin for Kibana, did you restart the Kibana service?

Could you try the next things:
R1. Could you give it a try to https://documentation.wazuh.com/current/user-manual/kibana-app/troubleshooting.html#wazuh-kibana-plugin-page-goes-blank ?
R2. Try with another browser to access Kibana and go to the Wazuh plugin.

**Comment by Desvelao** [comment]
Hi @yadiosl ,

I am glad you solved the problem. Thank you so much for the response! Your case could help other users.
