### ISSUE TITLE
Data could not be fetched in agent's FIM events

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-kibana-app#4104]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.x     | 4301-1| Basic, ODFE, Xpack |

| Browser |
| ------- |
| Firefox|

**Description**
When accessing an agent, if we click on the path of any FIM event, we cannot obtain information. In addition, the option to see the complete error does not work.

**Preconditions*
1. Demo environment

**Steps to reproduce**
1. Navigate to Agents>Specific agent
3. Click on FIM: Recent events>Path
4. Click on See the full error

**Expected Result**
1. Get more information
2. If it fails, see the full error

**Actual Result**
1. Data could not be fetched for `/tmp/agent.conf`
2. See full error button does nothing

**Screenshots**
```
Uncaught TypeError: right-hand side of 'in' should be an object, got boolean
```

https://user-images.githubusercontent.com/80041853/165348662-505c5f07-47b6-4ad0-ba6f-4d8dc8311232.mp4

**Comment by gdiazlo** [comment]
The API does not return data sometimes in the environment. The UI does not render the error adequately.

![image](https://user-images.githubusercontent.com/2181918/165903517-47407376-bab2-4b04-84c2-8f68c4e06c34.png)

**Comment by davidjiglesias** [comment]
The failing paths do not appear to be included in the agent's inventory. We need to further investigate the error and check the database. It might be related with a problem in FIM core side.

**Comment by gdiazlo** [comment]
The issue with the toast not showing an error string and the button of ¨Show the full error¨ not working might be related to https://github.com/wazuh/wazuh-kibana-app/issues/4030

**Comment by davidjiglesias** [comment]
We need to confirm is this error appears in previous versions.

**Comment by mauceballos** [comment]
testing on kibana 7.10 OK

![error-toast](https://user-images.githubusercontent.com/76791841/165996064-2285d6e5-7fe8-483a-a9ba-97de0244caec.gif)

**Comment by davidjiglesias** [comment]
I reopen this issue as the toast was fixed but some paths do not return any information when they should.

**Comment by j2vielchi** [comment]
Hello, greetings to the community.

I would like to know if this point could be solved. I currently have wazuh version 4.7.5, app revision: 02 and I have this problem:

Data could not be fetched for c:\users\user\directory\file.txt (example)

Full error:

Error: File not found at FlyoutDetail._callee$ (https://xxxxx/47402/bundles/plugin/wazuh/wazuh.chunk.10.js:1:6181020) at tryCatch (https://xxxxx/47402/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:786910) at Generator.invoke [as _invoke] (https://xxxxx/47402/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:790926) at Generator.next (https://xxxxx/47402/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:788105) at flyout_ asyncGeneratorStep (https://xxxxx/47402/bundles/plugin/wazuh/wazuh.chunk.10.js:1:6175519) at _next (https://xxxxx/47402/bundles/plugin/wazuh/wazuh.chunk.10.js:1:6175836)

**Comment by j2vielchi** [comment]
Hello, greetings to the community.

I would like to know if this point could be solved. I currently have wazuh version 4.7.5, app revision: 02 and I have this problem:

Data could not be fetched for c:\users\user\directory\file.txt (example)

Full error:

Error: File not found at FlyoutDetail._callee$ (https://xxxxx/47402/bundles/plugin/wazuh/wazuh.chunk.10.js:1:6181020) at tryCatch (https://xxxxx/47402/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:786910) at Generator.invoke [as _invoke] (https://xxxxx/47402/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:790926) at Generator.next (https://xxxxx/47402/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:788105) at flyout_ asyncGeneratorStep (https://xxxxx/47402/bundles/plugin/wazuh/wazuh.chunk.10.js:1:6175519) at _next (https://xxxxx/47402/bundles/plugin/wazuh/wazuh.chunk.10.js:1:6175836)

**Comment by j2vielchi** [comment]
Hello, I would like to know if the issue discussed was resolved??

**Comment by Tools-Security-Integrations** [comment]
NO still issue appears and many users face this issue, i think all
