### ISSUE TITLE
API version: Network Error

### ISSUE THREAD

**Issue by Fabian1976** [wazuh/wazuh-kibana-app#4423]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.7 | 7.17.5  | 4308 |  Xpack |

| Browser |
| ------- |
| Chrome |

**Description**
The wazuh-app displays `[API version] Network Error` when trying to open it

**Preconditions**
1. The API is configured properly and is displaying `Online`
2. CURL requests work fine
Example CURL code:
```
TOKEN=$(curl -u wazuh-wui:<password> -k -X GET "https://$(hostname):55000/security/user/authenticate?raw=true")
curl -k -X GET "https://$(hostname):55000/?pretty=true" -H "Authorization: Bearer $TOKEN"
```
Output:
```
{
   "data": {
      "title": "Wazuh API REST",
      "api_version": "4.3.7",
      "revision": 40320,
      "license_name": "GPL 2.0",
      "license_url": "https://github.com/wazuh/wazuh/blob/4.3/LICENSE",
      "hostname": "***redacted***",
      "timestamp": "2022-08-30T09:46:10Z"
   },
   "error": 0
}
```

**Steps to reproduce**
1. Just trying to open the Wazuh plugin

**Expected Result**
1. The app

**Actual Result**
1. Error `[API version] Network Error`
Detailed error:
```
Error: Network Error
    at e.exports (http://kibana.tux.o.mcare.lan/46953/bundles/plugin/wazuh/4.3.7-4308/wazuh.plugin.js:3:5282)
    at h.onerror (http://kibana.tux.o.mcare.lan/46953/bundles/plugin/wazuh/4.3.7-4308/wazuh.plugin.js:3:4252)
```

**Additional context**
The contents of the `/usr/share/kibana/data/wazuh/config/wazuh.yml` file:
```
hosts:
  - dev:
      url: https://*redacted*
      port: 55000
      username: wazuh-wui
      password: *redacted*
      run_as: false
```

Kibana is running with the `kibana_system` user.

**Comment by Machi3mfl** [comment]
Hi @Fabian1976. Thanks for contacting us.
Can you tell me more about your environment? What versions do you have installed? Do you have installed wazuh dashboard? 
Do you have access to the Wazuh UI from your browser?
Please, can you add a screenshot where you see the error message: `[API version] Network Error`.
The error could be related to the wazuh API version, keep in mind that all the version must match. 
(indexer version - wazuh api version - dashboard).

**Comment by Fabian1976** [comment]
This is the error i get when trying to open the dashboard in Kibana:
![image](https://user-images.githubusercontent.com/9444852/188069167-2d346167-6d01-4d41-9902-8c63e1398ea7.png)

All versions match up:
* wazuh-manager: 4.3.7
* wazuh-kibana-app: 4.3.7
* Elasticsearch: 7.17.5
* Kibana: 7.17.5
The API version is allready displayed in initial post (also 4.3.7).

**Comment by gdiazlo** [comment]
@Fabian1976 did you update your Wazuh installation recently or it is a new deployment? The application caches aggressively to decrease load times. If you updated recently, this may happen because the browser still has the older version cached. Can you try cleaning the browser cache or maybe in an incognito/private browser window?

**Comment by Fabian1976** [comment]
It is an update.
I have cleared the cache and with dev-tools open in chrome disabled the cache, but still no luck:
![image](https://user-images.githubusercontent.com/9444852/188084269-92c6f9b7-66ce-43d5-a213-28bf795def53.png)

**Comment by gdiazlo** [comment]
@Fabian1976 thanks for taking your time to report all of this. We need to ensure the installed app is indeed the version we think it is. So we can further diagnose what could have gone wrong.

For that, in the screenshot you posted, if you click on the blue icon on the right side of the `Check Wazuh API version` message, an expanded view of the error should appear, can you check it? It should give us more information about the error and the versions the app believe it is working with.

Ps.
If you have a Slack account,[ join us](https://wazuh.com/community/join-us-on-slack/)!

**Comment by Fabian1976** [comment]
No problem. I would also like to fix this.

It shows this error:
```
INFO: Current API in cookie: [dev]
INFO: Getting API version data...
ERROR: Network Error
```

The Network Error implies no connectivity. But a manual curl works fine.

**Comment by gdiazlo** [comment]
I see, to diagnose this error, can you share more details about your deployment? 

From what you said previously, I would guess you have a cluster of elasticsearch, a dedicated kibana node with Wazuh installed, and a single node (or cluster) Wazuh server.

If this is the case, the error you're experiencing could mean the kibana machine is unable to reach the Wazuh server API. So to test it, the curl must be run from inside the kibana machine, to test if it works.

To test the endpoint, you can also click on the [Go to settings] button, and there you will see the API which is currently configured, so you can check if the data there matches the data you used in the curl test.

If it does not match, you might need to update the wazuh.yml  file in `/usr/share/kibana/data/wazuh/config/wazuh.yml `

**Comment by Fabian1976** [comment]
You are right about the setup. An Elasticsearch cluster with a seperate Kibana instance with the Wazuh-app installed and a seperate Wazuh-manager.

The curl command pasted in the first post was allready performed from the Kibana host. So the network connection is also functioning.

When i check the API settings in the Wazuh-app in Kibana, it also says the API is online (see screenshot):
![image](https://user-images.githubusercontent.com/9444852/188168592-80c91662-6bf8-4fd2-88ed-dfca15020700.png)

The previous screenshot also had a green tick behind the "Check Wazuh API connection".

I don't what else to share that can be usefull for you.

I will try and install the same setup on an instance which doesn't have X-pack installed, but i don't see any errors related to that.
