### ISSUE TITLE
Wazuh App fails to list rules when a variable is used to define the rule level.

### ISSUE THREAD

**Issue by ArielIvanOjeda** [wazuh/wazuh-kibana-app#4495]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.1-rev 40311| Server | Manager | Packages | Any |

Hello Team,

There seems to be an issue when using a variable for the rule level. The rules work fine, but when trying to list the rules from the Kibana interface, by going to Wazuh-Management-Rules, the interface clocks and displays an error. This does not happen when Listing files, only when listing rules after the file for the rules that use the variable for the rule level, is uploaded to the Manager. There is no error when saving the file from the Kibana interface and no error when restarting the Manager. This was tested in 4.2.4 too and the same happens.

## Steps to reproduce

- Add the rule to the Wazuh Manager.
Example:

```
<var name="LEVEL">0</var>
<rule id="100101" level="$LEVEL">
```

- Go to Wazuh->Management->Rules.

## Expected results

The Wazuh Kibana interface should list the complete ruleset.

## Current results

The interface fails to display the rules list and clocks until an error is displayed.
"Error when getting the items of rules"

![Error in 4 3 1](https://user-images.githubusercontent.com/97059668/170502509-a71f1b74-c26a-44ab-9c28-edf8281dc65a.jpg)

**Comment by asteriscos** [comment]
# Test

After replicating the issue I could check the `GET /rules` request error is thrown by Wazuh API:

![image](https://user-images.githubusercontent.com/9343732/200376635-47ba540a-2442-4659-80fb-8fda39c0d666.png)

Wazuh API logs:

```

022/11/07 17:30:38 ERROR: Error executing API request locally: invalid literal for int() with base 10: '$LEVEL'
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 243, in run_local
    data = f(**f_kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.0-py3.9.egg/wazuh/rule.py", line 71, in get_rules
    rules.extend(load_rules_from_file(rule_file['filename'], rule_file['relative_dirname'], rule_file['status']))
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.0-py3.9.egg/wazuh/core/rule.py", line 82, in load_rules_from_file
    'id': int(xml_rule.attrib['id']), 'level': int(xml_rule.attrib['level']),
ValueError: invalid literal for int() with base 10: '$LEVEL'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 288, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
ValueError: invalid literal for int() with base 10: '$LEVEL'

```


The rule saved was:

```

<group name="local,syslog,sshd,">

  <!--
  Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2
  -->
  <var name="LEVEL">0</var>
  <rule id="100001" level="$LEVEL">
    <if_sid>5716</if_sid>
    <srcip>1.1.1.1</srcip>
    <description>sshd: authentication failed from IP 1.1.1.1.</description>
    <group>authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,</group>
  </rule>
</group>

```
