### ISSUE TITLE
Error in login "Cookie “security_authentication” has been rejected because it is already expired

### ISSUE THREAD

**Issue by giper45** [wazuh/wazuh-kibana-app#4536]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.1.5     | 1.13.2      | na| Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|   

Docker environment.  

**Description**
Hello, we have a wazuh docker instance installed in production environment.
Unfortunately, without any update, we encounter the following error in the login:
![image](https://user-images.githubusercontent.com/18548727/190599875-9732c304-1f58-464e-8134-0ad64a259e26.png)

The error seems to be related with an unstable kibana version issue:
https://github.com/wazuh/wazuh-kibana-app/issues/4108

The error is related with

Anyway, we did not perform any update on the envirnoment and it always worked in the years.
We use the following docker images (production-cluster.yml environment):
```  
image: wazuh/wazuh-odfe:4.1.5    
image: amazon/opendistro-for-elasticsearch:1.13.2                                                                      
image: wazuh/wazuh-kibana-odfe:4.1.5                                                                                   

```  
Could you give us a solution?
Thank you very much in advance.

**Comment by AlexRuiz7** [comment]
Hello @giper45 

Thank you for reporting this issue to us.

I'll further investigate and read the matter, and I'll get back to you as soon as possible.

Best regards,
Alex

**Comment by giper45** [comment]
Hi @AlexRuiz7 , I have partially solved the problem of the login and it did not seem to be related with those errors that still remain. 
Note that the current Wazuh version do not seem to present the bug. 
When I navigate the current url:  
```
https://<wazuh_site>/app/login?nextUrl=%2F 
```

The login properly works, and the user is redirected to the Wazuh dashboard page. 

If I navigate the current url:    
```
https://<wazuh_site>/app/login 
``` 

The user is redirected to the previous URL, and everything is okay.
However, if I navigate the following url:    
```
https://<wazuh_site>/app/login      
``` 


The redirect to the url containing nextUrl parameter does not occur, and the login authentication always redirects to the login page.

**Comment by AlexRuiz7** [comment]
I see, looks like navigating to `/app/login` does redirect to the login page, and logouts the users. Am I right?

**Comment by giper45** [comment]
Hi, do not know if the login occurs and then a logout occurs. 
I just know that when the POST request occurs in the `/app/login` page (without the `nextUrl` parameter), the authentication does not fail (there is no wrong username / password error) , but the user is still not authenticated (maybe because he was logout)

**Comment by AlexRuiz7** [comment]
Hi @giper45 

It's still not clear to me if you are able to log into Kibana correctly, in despite of the error.

If I'm understanding this correctly, it does fail only if the `/app/login` does not contain the `nextUrl` parameter. Is that right?

**Comment by giper45** [comment]
Behavior when the `/app/login` does not contain the `nextUrl`:
![invalid2](https://user-images.githubusercontent.com/18548727/191216464-fb0ab26c-75b6-4427-84c9-76883fb13eb8.gif)

**Comment by AlexRuiz7** [comment]
Thanks @giper45, it's much clearer now. I was able to reproduce the problem.

The login flow is managed by the security plugin of OpenDistro.

Here's the message I got:
```js
failed to get user tenant: Error: Unauthorized
core.entry.js:13 Detected an unhandled Promise rejection.
Error: Unauthorized
core.entry.js:6 Uncaught (in promise) Error: Unauthorized
    at Fetch._callee3$ (core.entry.js:6:59535)
    at tryCatch (opendistroQueryWorkbenchKibana.plugin.js:1:32004)
    at Generator.invoke [as _invoke] (opendistroQueryWorkbenchKibana.plugin.js:1:35968)
    at forEach.prototype.<computed> [as next] (opendistroQueryWorkbenchKibana.plugin.js:1:33129)
    at fetch_asyncGeneratorStep (core.entry.js:6:526
```

I've also confirmed that there is no problem if using the `https://<wazuh_site>/app/login?nextUrl=%2F` URL. In this case, the user is logged in successfully.

Furthermore, navigating to `https://<wazuh_site>` or `https://<wazuh_site>/` redirects to `https://<wazuh_site>/app/login?nextUrl=%2F` automatically (resolved by the ODFE plugin as I said), resulting in a successful login.

My only possible advice is not to use the `https://<wazuh_site>/app/login` explicitly, as it's proven to force this bug.

As explained, this section is managed by ODFE, a third-party software which is abandoned in favor of OpenSearch, which we already support in newer versions, and where I've checked that this problem is not present.

For all these reasons, I'll close this issue, not before thanking you by your contribution to our project by reporting bugs like this, and to suggest you [upgrading Wazuh](https://documentation.wazuh.com/current/upgrade-guide/upgrading-central-components.html) to a compatible version with OpenSearch (4.3.8, or the upcoming 4.4.0).
