### ISSUE TITLE
Wrong FIM report

### ISSUE THREAD

**Issue by mauceballos** [wazuh/wazuh-kibana-app#4621]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.8   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
An error message is displayed when we like to generate a report on the FIM dashboard module.

**Preconditions**
1. Add All Sample Data 
2. Up DevTool on Browser, network tab

**Steps to reproduce**
1. Navigate to the Integrity monitoring module
2. Click on Generate report option
3. the error pop-up is displayed.

**Expected Result**
1.  Should generate the pop-up success

**Actual Result**
1. the error on the pop-up:

```
Error: 5029 - Reporting was aborted (Cannot read property 'os' of undefined)
    at createError (https://192.168.1.160/1/bundles/plugin/wazuh/wazuh.plugin.js:2:31654)
    at settle (https://192.168.1.160/1/bundles/plugin/wazuh/wazuh.plugin.js:8:15184)
    at XMLHttpRequest.onloadend (https://192.168.1.160/1/bundles/plugin/wazuh/wazuh.plugin.js:2:29447)

```
**Screenshots**
<details>

![Screenshot from 2022-09-28 15-37-43](https://user-images.githubusercontent.com/76791841/192866013-ebb8f1d2-2e77-4f4b-ae3f-e6cdef4563b2.png)

![Screenshot from 2022-09-28 15-15-05](https://user-images.githubusercontent.com/76791841/192866020-15521243-ac49-45c6-9b8b-b33305909ec0.png)

</details>

**Comment by JuanGarriuz** [comment]
## Update 4.10

https://github.com/user-attachments/assets/1ce7eb16-b82e-464f-87f5-c04e3a84af27

**Comment by Desvelao** [comment]
According to the research, this problem is not present in the current application (4.10.1), so we could close the issue as not planned.
