### ISSUE TITLE
`Cannot read properties of null` error in the Settings section

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#4772]
**Description**
When leaving the `Configuration` tab from the Settings section, a `cannot read properties of null` error is shown in the browser's console.

**Steps to reproduce**
1. Navigate to 'Settings < Configuration'
2. Navigate to any other section of the app.
3. See the error in the browser's console.

**Screenshots**

![image](https://user-images.githubusercontent.com/15186973/198563646-29aaba3d-17ba-48fe-a806-b1577b321df1.png)

**Additional context**

<details>
  <summary>Error log</summary>
  
  ```js
  Subscriber.js:69 Uncaught TypeError: Cannot read properties of null (reading 'closed')
      at __kbnSharedDeps__.../../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.unsubscribe (Subscriber.js:69:1)
      at HTMLUnknownElement.callCallback (react-dom.development.js:336:1)
      at Object.invokeGuardedCallbackDev (react-dom.development.js:385:1)
      at invokeGuardedCallback (react-dom.development.js:440:1)
      at safelyCallDestroy (react-dom.development.js:21933:1)
      at react-dom.development.js:22374:1
      at unstable_runWithPriority (scheduler.development.js:697:1)
      at runWithPriority$2 (react-dom.development.js:12149:1)
      at commitUnmount (react-dom.development.js:22367:1)
      at unmountHostComponents (react-dom.development.js:22860:1)
  __kbnSharedDeps__.../../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.unsubscribe @ Subscriber.js:69
  callCallback @ react-dom.development.js:336
  invokeGuardedCallbackDev @ react-dom.development.js:385
  invokeGuardedCallback @ react-dom.development.js:440
  safelyCallDestroy @ react-dom.development.js:21933
  (anonymous) @ react-dom.development.js:22374
  unstable_runWithPriority @ scheduler.development.js:697
  runWithPriority$2 @ react-dom.development.js:12149
  commitUnmount @ react-dom.development.js:22367
  unmountHostComponents @ react-dom.development.js:22860
  commitDeletion @ react-dom.development.js:22896
  commitMutationEffects @ react-dom.development.js:25323
  callCallback @ react-dom.development.js:336
  invokeGuardedCallbackDev @ react-dom.development.js:385
  invokeGuardedCallback @ react-dom.development.js:440
  commitRootImpl @ react-dom.development.js:25050
  unstable_runWithPriority @ scheduler.development.js:697
  runWithPriority$2 @ react-dom.development.js:12149
  commitRoot @ react-dom.development.js:24922
  finishSyncRender @ react-dom.development.js:24329
  performSyncWorkOnRoot @ react-dom.development.js:24307
  scheduleUpdateOnFiber @ react-dom.development.js:23698
  updateContainer @ react-dom.development.js:27103
  legacyRenderSubtreeIntoContainer @ react-dom.development.js:27544
  (anonymous) @ react-dom.development.js:27649
  unbatchedUpdates @ react-dom.development.js:24433
  unmountComponentAtNode @ react-dom.development.js:27648
  (anonymous) @ ngReact.js:219
  $broadcast @ angular.js:19788
  $destroy @ angular.js:19402
  ngIfWatchAction @ angular.js:29573
  $digest @ angular.js:19208
  $apply @ angular.js:19568
  wrapped @ ngReact.js:70
  (anonymous) @ tabs.js:25
  onClick @ tabs.js:42
  callCallback @ react-dom.development.js:336
  invokeGuardedCallbackDev @ react-dom.development.js:385
  invokeGuardedCallback @ react-dom.development.js:440
  invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:454
  executeDispatch @ react-dom.development.js:584
  executeDispatchesInOrder @ react-dom.development.js:609
  executeDispatchesAndRelease @ react-dom.development.js:713
  executeDispatchesAndReleaseTopLevel @ react-dom.development.js:722
  forEachAccumulated @ react-dom.development.js:694
  runEventsInBatch @ react-dom.development.js:739
  runExtractedPluginEventsInBatch @ react-dom.development.js:880
  handleTopLevel @ react-dom.development.js:5803
  batchedEventUpdates$1 @ react-dom.development.js:24401
  batchedEventUpdates @ react-dom.development.js:1415
  dispatchEventForPluginEventSystem @ react-dom.development.js:5894
  attemptToDispatchEvent @ react-dom.development.js:6010
  dispatchEvent @ react-dom.development.js:5914
  unstable_runWithPriority @ scheduler.development.js:697
  runWithPriority$2 @ react-dom.development.js:12149
  discreteUpdates$1 @ react-dom.development.js:24417
  discreteUpdates @ react-dom.development.js:1438
  dispatchDiscreteEvent @ react-dom.development.js:5881
  ```
</details>

**Comment by chantal-kelm** [comment]
This issue was solved in this [PR](https://github.com/wazuh/wazuh-kibana-app/pull/5135)
