### ISSUE TITLE
Compatibility with Wazuh Dashboard based on OpenSearch 1.3

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#5294]
## Description
We need to ensure the UI compatibility with a new version of Wazuh Dashboard 4.3.10 based on OpenSearch Dashboards.

For that, we need to:

- [x] Review OpenSearch and OpenSearch Dashboards release notes for v1.3.0. 
- [x] Identify improvements and potential impact on the UI.
- [x] Develop a testing environment to verify our components would work under this new build.

## Issues
-  None

**Comment by AlexRuiz7** [comment]
### Release notes and potential issues

#### [1.3.0]

Potential issues:

- None

Interesting issues:

- [CVE] Decode anchor ID in Discover (#1327) (#1332)
- Bumps node-fetch from v2.6.1 to v2.6.7 (#1169) (#1221)
- Don't terminate the server on NodeDeprecationWarning (#1185) (#1210)


[1.3.0]: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/release-notes/opensearch-dashboards.release-notes-1.3.0.md

**Comment by AlexRuiz7** [comment]
### Testing on a production environment

I've created a Dockerized demo environment of OpenSearch 1.3.8, following the Docker Compose examples published in their [docs][docs]. This environment is composed by the following nodes:

- opensearch-indexer:1.3.8
- opensearch-dashboard:1.3.8
- imposter(wazuh-api):4.3.10
- filebeat

The imposter node mocks the Wazuh API at version 4.3.10, while the Filebeat node is used to set up the Wazuh ingest pipelines and field mappings required by the app.

The app has been built OpenSearch 1.3.8, then installed using the usual procedure:

```bash
bin/opensearch-dashboards-plugin install file://<path_to_pkg>/wazuh-1.3.8.zip
```
In my case, the package was copied to the container to the path `/tmp/pkgs`


Some navigating across the have probes that the app is working correctly. sample data has been used.

* OpenSearch version
![image](https://user-images.githubusercontent.com/15186973/225320959-de6316f0-f66a-4810-8155-6d6c1ee1307f.png)

* Wazuh app version
![image](https://user-images.githubusercontent.com/15186973/225321056-be7f9800-7cb4-4455-b6a0-cfa19e655e58.png)

* Module directory
![image](https://user-images.githubusercontent.com/15186973/225321126-1dbcab1b-4202-4df9-a138-c71a4f5cdcaf.png)

* Security events module (dashboard)
![image](https://user-images.githubusercontent.com/15186973/225321453-c05a1368-acf5-41b0-a852-0946efee7d13.png)

* Security events module (events)
![image](https://user-images.githubusercontent.com/15186973/225321530-d1eded76-83b6-47a8-b0ad-ac5f0b90eb9c.png)

* Agent's dashboard
![image](https://user-images.githubusercontent.com/15186973/225321717-730a8ee3-a5a4-47fd-accc-eb30f909ede7.png)

However, this error shows in the console each time the app is accessed. The error is from the `reporstsDashboards` plugin. **We do not use this plugin, so it's safe to omit it. Furthermore, no side effects have been detected.** Our PDF and CSV reports are generated without problem.

```js
reportsDashboards.plugin.js:24 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'split')
    at _callee4$ (reportsDashboards.plugin.js:24:123690)
    at tryCatch (reportsDashboards.plugin.js:24:102608)
    at Generator.invoke [as _invoke] (reportsDashboards.plugin.js:24:106559)
    at Generator.next (reportsDashboards.plugin.js:24:103747)
    at asyncGeneratorStep (reportsDashboards.plugin.js:1:71573)
    at _next (reportsDashboards.plugin.js:1:71884)
    at reportsDashboards.plugin.js:1:72034
    at new Promise (<anonymous>)
    at reportsDashboards.plugin.js:1:71796
    at checkURLParams (reportsDashboards.plugin.js:24:124832)
```


[docs]: https://opensearch.org/docs/1.3/install-and-configure/install-opensearch/docker/#sample-docker-composeyml
