### ISSUE TITLE
reportsDashboards error in console - compatibility OpenSearch 2.6 & 1.3

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-kibana-app#5332]
| Wazuh | OpenSearch | 
| ----- | ------- | 
| 4.4   | 1.3 & 2.6     | 

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
During the [compatibility test with OpenSearch 2.6](https://github.com/wazuh/wazuh-kibana-app/issues/5263#issuecomment-1458614877) we found an error in the console as soon as Wazuh app loads the home module.
It doesn't seem to affect any of Wazuh features.

This error can also be replicated in OpenSearch 1.3.

```js
reportsDashboards.plugin.js:24 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'split')
    at _callee4$ (reportsDashboards.plugin.js:24:201073)
    at tryCatch (reportsDashboards.plugin.js:24:180012)
    at Generator.invoke [as _invoke] (reportsDashboards.plugin.js:24:183963)
    at Generator.next (reportsDashboards.plugin.js:24:181151)
    at asyncGeneratorStep (reportsDashboards.plugin.js:1:73707)
    at _next (reportsDashboards.plugin.js:1:74018)
    at reportsDashboards.plugin.js:1:74168
    at new Promise (<anonymous>)
    at reportsDashboards.plugin.js:1:73930
    at checkURLParams (reportsDashboards.plugin.js:24:202215)
```

**Steps to reproduce**
1. Navigate to Wazuh modules home
2. Open the dev tools
3. See the error

**Screenshots**
![image](https://user-images.githubusercontent.com/9343732/228301289-a1a2c650-da50-45e6-9c03-0aa332cb605d.png)

**Comment by asteriscos** [comment]
Closed as not planned.
