### ISSUE TITLE
Fix the request body suggestions are not working in API console

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#5520]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
The request body suggestions are not working in the API console.

**Steps to reproduce**
1. Navigate to Tools/API Console
2. Add the following request
```
PUT /logtest
{

}
```
3. Set the cursor in the request body between `{` and `}` and type a `"` character. The body suggestion is not displayed.
```
PUT /logtest
{
  "
}
```

Related error:
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/01effe82-86d3-44ba-985d-b19c08f4c441)

```
dev-tools.ts:578 Uncaught TypeError: chain.replace is not a function
    at dev-tools.ts:578:1
    at Array.map (<anonymous>)
    at getDictionary (dev-tools.ts:573:1)
    at dev-tools.ts:598:1
    at CodeMirror.showHint (show-hint.js:21:1)
    at _utils_codemirror_lib_codemirror__WEBPACK_IMPORTED_MODULE_0___default.a.commands.autocomplete (dev-tools.ts:89:1)
    at CodeMirror$1.execCommand (codemirror.js:12493:1)
    at dev-tools.ts:357:1
    at signal (codemirror.js:1724:1)
    at signalDOMEvent (codemirror.js:1741:1)
```

**Comment by Desvelao** [comment]
# Research

The error is caused because the request body hints are not a string, so fail when trying to use a string method. 

Ensuring the string method is only used for these hints should solve the problem.

I created a pull request that fixes this problem: https://github.com/wazuh/wazuh-kibana-app/pull/5521
