### ISSUE TITLE
[BUG] Rule editor in UI throws 3013 Internal Error when using "&" in rules

### ISSUE THREAD

**Issue by mimugmail** [wazuh/wazuh-kibana-app#5666]
**Describe the bug**

I'm trying to exclude a URL value from a apache decoded log which contains something like:

`Container/&dataid=`

If I do so in UI I get from Wazuh-Dashboard:

```
Error: 3013 - Wazuh Internal Error
    at createError (https://172.42.42.71/44401/bundles/plugin/wazuh/wazuh.plugin.js:2:28658)
    at settle (https://172.42.42.71/44401/bundles/plugin/wazuh/wazuh.plugin.js:8:19613)
    at XMLHttpRequest.onloadend (https://172.42.42.71/44401/bundles/plugin/wazuh/wazuh.plugin.js:2:26451)

```
When using the CLI to the edit the file it works fine and also the affected part is excluded from altering.

**To Reproduce**
1. Go to rule editor
2. Add a local_rule with matching something with "&"
3. See the error

**OpenSearch Version**
Latest Wazuh-Indexed 4.4.4

**Dashboards Version**
Latest Wazuh-Dashboard 4.4.4

**Plugins**
Vanilla install with any fancy modifications

**Host/Environment (please complete the following information):**
 - OS: Debian 11
 - Browser and version: Chrome latest

**Comment by mimugmail** [comment]
Hi,

no it's the apache decoder. I'm using the rule to catch 4XX errors but want to exclude custom URI's

**Comment by AlexRuiz7** [comment]
Hello @mimugmail 

Can you extend the steps provided to reproduce the problem?

In the meantime, let me share with you this documentation about custom rules and decoders.

Thanks in advance!

**Comment by AlexRuiz7** [comment]
Closing due to inactivity. Feel free to re-open the issue if required.
