### ISSUE TITLE
5029 - Reporting was aborted - no such file or directory

### ISSUE THREAD

**Issue by Rohr2827** [wazuh/wazuh-kibana-app#5739]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
App version: 4.4.5
App revision: 02

| Browser |
| ------- |
| Microsoft Edge|

**Description**
After updating Wazuh from version 4.3.10 -> 4.4.5 everything seems to be working except manually generated reports in the top right corner of the Wazuh dashboard on security events, inventory data, etc. Whenever I press the generate report button it starts to generate but then gets an error which I will provide below. 

**Steps to reproduce**
1. Not sure how to reproduce on different system. When updating a different Wazuh server from 4.3.11 -> 4.4.5 no errors occurred, and everything seems to work as expected, however, these different servers were made very recently to try to reproduce the error.

**Expected Result**
1. Generated report

**Actual Result**
1. Error creating the report
5029 - Reporting was aborted - no such file or directory

**Screenshots**
![Capture](https://github.com/wazuh/wazuh-kibana-app/assets/140717036/2066f73d-a580-46e8-8759-645f3d32ad2b)

Error: 5029 - Reporting was aborted - no such file or directory
    at createError (/bundles/plugin/wazuh/wazuh.plugin.js:2:28658)
    at settle (/bundles/plugin/wazuh/wazuh.plugin.js:8:19613)
    at XMLHttpRequest.onloadend (/bundles/plugin/wazuh/wazuh.plugin.js:2:26451)

**Comment by Rohr2827** [comment]
Resolved issue by changing report image inside of GUI by going to wazuh->settings->PDF reports logo then putting in a custom image.png. Then when you remove the custom image Wazuh will be able to find the path to the default image and fix the issue.
